### PR TITLE
Allow to toggle notes' position with a shortcut

### PR DESCRIPTION
**Pull request by themighty1**
I had to change use-shortcut to use-visibility-shortcut. Will this break the existing settings for those who upgrade from an earlier version?
if so, I can revert back to the name use-shortcut.

### CODE REVIEW

**Comment by themighty1** [comment]
@maoschanz , sure, no problem, I will change the names accordingly. And I will not implement anything else.

**Comment by themighty1** [comment]
@maoschanz, names changed, verified to work. Looking forward to your proper fix.

**Comment by themighty1** [comment]
@maoschanz , hi, are you happy with this PR?

**Comment by maoschanz** [comment]
it looks fine, i'm just busy with other things so i can't test it right now

**Pull request merged**
